# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Category.create([
  { :name => "Dinner", :created_at => "2013-07-08 17:58:30", :updated_at => "2013-07-08 17:58:30" },
  { :name => "Breakfast", :created_at => "2013-07-10 08:10:14", :updated_at => "2013-07-10 08:10:14" },
  { :name => "Lunch", :created_at => "2013-07-10 08:10:28", :updated_at => "2013-07-10 08:10:28" },
  { :name => "Snack", :created_at => "2013-07-10 08:10:50", :updated_at => "2013-07-10 08:10:50" },
  { :name => "Dessert", :created_at => "2013-07-10 08:11:03", :updated_at => "2013-07-10 08:11:03" }
], :without_protection => true )



Ingredient.create([
  { :name => "tomato", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "cheese", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "spaghetti", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "macaroni pasta", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "flour", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "salt", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "pepper", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "Italian herbs and seasonings", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "basil", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "ham", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "onions", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "milk", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "parmesan", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-06 10:09:10", :recipes => nil },
  { :name => "Butter", :created_at => "2013-07-06 16:22:33", :updated_at => "2013-07-06 16:22:33", :recipes => nil },
  { :name => "Lemon", :created_at => "2013-07-06 16:41:14", :updated_at => "2013-07-06 16:41:14", :recipes => nil },
  { :name => "Cream", :created_at => "2013-07-06 16:42:14", :updated_at => "2013-07-06 16:42:14", :recipes => nil },
  { :name => "Cloves yay", :created_at => "2013-07-06 16:42:52", :updated_at => "2013-07-07 18:35:38", :recipes => nil },
  { :name => "Vinegar", :created_at => "2013-07-07 18:37:40", :updated_at => "2013-07-07 18:37:40", :recipes => nil },
  { :name => "water", :created_at => "2013-07-08 10:40:17", :updated_at => "2013-07-08 10:40:17", :recipes => nil },
  { :name => "BACON", :created_at => "2013-07-08 15:25:41", :updated_at => "2013-07-08 15:25:41", :recipes => nil },
  { :name => "chocolate", :created_at => "2013-07-10 08:12:07", :updated_at => "2013-07-10 08:12:07", :recipes => nil },
  { :name => "sugar", :created_at => "2013-07-10 08:12:19", :updated_at => "2013-07-10 08:12:19", :recipes => nil }
], :without_protection => true )



IngredientsRecipe.create([
  { :ingredient_id => 144, :recipe_id => 7, :quantity => nil, :created_at => "2013-07-08 15:22:11", :updated_at => "2013-07-08 15:22:11" },
  { :ingredient_id => 165, :recipe_id => 12, :quantity => "20", :created_at => "2013-07-08 15:26:00", :updated_at => "2013-07-08 15:29:20" },
  { :ingredient_id => 144, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 145, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 146, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 149, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 150, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 151, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 152, :recipe_id => 5, :quantity => nil, :created_at => "2013-07-09 22:42:46", :updated_at => "2013-07-09 22:42:46" },
  { :ingredient_id => 148, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:01", :updated_at => "2013-07-10 08:12:01" },
  { :ingredient_id => 157, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:01", :updated_at => "2013-07-10 08:12:01" },
  { :ingredient_id => 159, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:01", :updated_at => "2013-07-10 08:12:01" },
  { :ingredient_id => 164, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:01", :updated_at => "2013-07-10 08:12:01" },
  { :ingredient_id => 166, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:31", :updated_at => "2013-07-10 08:12:31" },
  { :ingredient_id => 167, :recipe_id => 9, :quantity => nil, :created_at => "2013-07-10 08:12:31", :updated_at => "2013-07-10 08:12:31" },
  { :ingredient_id => 165, :recipe_id => 10, :quantity => nil, :created_at => "2013-07-10 08:12:49", :updated_at => "2013-07-10 08:12:49" },
  { :ingredient_id => 149, :recipe_id => 11, :quantity => nil, :created_at => "2013-07-10 08:13:14", :updated_at => "2013-07-10 08:13:14" },
  { :ingredient_id => 157, :recipe_id => 11, :quantity => nil, :created_at => "2013-07-10 10:41:12", :updated_at => "2013-07-10 10:41:12" },
  { :ingredient_id => 144, :recipe_id => 8, :quantity => "2", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:25" },
  { :ingredient_id => 149, :recipe_id => 8, :quantity => "1", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 150, :recipe_id => 8, :quantity => "3", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 151, :recipe_id => 8, :quantity => "2", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 152, :recipe_id => 8, :quantity => "4", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 154, :recipe_id => 8, :quantity => "2", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 164, :recipe_id => 8, :quantity => "5", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 165, :recipe_id => 8, :quantity => "3", :created_at => "2013-07-09 19:38:00", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 167, :recipe_id => 8, :quantity => "1", :created_at => "2013-07-10 08:30:51", :updated_at => "2013-07-11 14:05:26" },
  { :ingredient_id => 144, :recipe_id => 6, :quantity => "2", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 145, :recipe_id => 6, :quantity => "4", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 146, :recipe_id => 6, :quantity => "40", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 149, :recipe_id => 6, :quantity => "1", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 150, :recipe_id => 6, :quantity => "2", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 151, :recipe_id => 6, :quantity => "2", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 152, :recipe_id => 6, :quantity => "4", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 157, :recipe_id => 6, :quantity => "18", :created_at => "2013-07-10 10:39:35", :updated_at => "2013-07-11 14:11:51" },
  { :ingredient_id => 157, :recipe_id => 13, :quantity => "40", :created_at => "2013-07-08 15:46:48", :updated_at => "2013-07-11 14:14:13" },
  { :ingredient_id => 166, :recipe_id => 13, :quantity => "12", :created_at => "2013-07-10 08:34:13", :updated_at => "2013-07-11 14:14:13" },
  { :ingredient_id => 167, :recipe_id => 13, :quantity => "2", :created_at => "2013-07-10 08:34:13", :updated_at => "2013-07-11 14:14:13" },
  { :ingredient_id => 144, :recipe_id => 4, :quantity => "20", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 145, :recipe_id => 4, :quantity => "4", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 147, :recipe_id => 4, :quantity => "50", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 148, :recipe_id => 4, :quantity => "12", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 149, :recipe_id => 4, :quantity => "4", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 150, :recipe_id => 4, :quantity => "2", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 151, :recipe_id => 4, :quantity => "2", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 154, :recipe_id => 4, :quantity => "3", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 155, :recipe_id => 4, :quantity => "2", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 157, :recipe_id => 4, :quantity => "20", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" },
  { :ingredient_id => 164, :recipe_id => 4, :quantity => "4", :created_at => "2013-07-10 10:35:30", :updated_at => "2013-07-11 14:14:59" }
], :without_protection => true )



Recipe.create([
  { :name => "Brownies", :cook_time => "EVER", :instructions => "EAT THEM ALWAYS", :created_at => "2013-07-08 15:46:48", :updated_at => "2013-07-10 10:34:50", :category_id => 5, :recipe_image => "brownie.jpg" },
  { :name => "Macaroni and Cheese", :cook_time => "1 hour", :instructions => "Combine the macaroni with the cheese and bake for 1 hour.", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-10 10:35:30", :category_id => 1, :recipe_image => "mac_and_cheese.jpg" },
  { :name => "Soup", :cook_time => "15 min", :instructions => "Make soup", :created_at => "2013-07-06 17:04:20", :updated_at => "2013-07-10 10:35:51", :category_id => 1, :recipe_image => "Soup.jpg" },
  { :name => "Spaghetti", :cook_time => "20 minutes", :instructions => "Place spaghetti in boiling water for 12 minutes, then add tomato sauce and herbs and heat for a further 3 minutes. Remove from heat and place in a bowl for eating. Add parmesan cheese and fresh basil.", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-10 10:39:35", :category_id => 1, :recipe_image => "spaghetti.jpg" },
  { :name => "Pizza", :cook_time => "1.5 hours", :instructions => "Make the dough, roll it out flat, cover with tomato sauce and cheese and add any desired toppings. Place in oven for 1 hour.", :created_at => "2013-07-06 10:09:10", :updated_at => "2013-07-10 10:39:50", :category_id => 1, :recipe_image => "Pizza.jpg" },
  { :name => "Cake Obvs", :cook_time => "45 min", :instructions => "Bake a cake with chocolate and stuff", :created_at => "2013-07-07 18:22:17", :updated_at => "2013-07-10 10:40:08", :category_id => 5, :recipe_image => "Cake.jpg" },
  { :name => "Disaster", :cook_time => "0", :instructions => "RUN AWAY", :created_at => "2013-07-07 18:37:09", :updated_at => "2013-07-10 10:40:27", :category_id => 5, :recipe_image => "THE_INTERNET.jpeg" },
  { :name => "Corn", :cook_time => "1 hour", :instructions => "Cook it", :created_at => "2013-07-08 11:09:50", :updated_at => "2013-07-10 10:41:12", :category_id => 4, :recipe_image => "corn.jpg" }
], :without_protection => true )



User.create([
  { :email => "heyyou", :password_digest => "$2a$10$fUafu4QPQaE.6vjB8EOoe.eRh.vDQqa3Ry7Qyu8omBw3lIA76P0Ha", :created_at => "2013-07-09 13:00:40", :updated_at => "2013-07-09 15:36:31", :role => "user" },
  { :email => "andrea", :password_digest => "$2a$10$kdL16bF8jB8mgXy5D1HEi.8PXvzvDbDuwpJaJwgAxPkzsFWtl4WXK", :created_at => "2013-07-09 12:37:24", :updated_at => "2013-07-09 15:36:47", :role => "admin" },
  { :email => "DOG", :password_digest => "$2a$10$oDLbkKpJgOcSJs2yUdcC5.NXr8GNB8WEiA/SH290uj/jOkPrQrUZi", :created_at => "2013-07-09 12:59:00", :updated_at => "2013-07-09 15:57:49", :role => "admin" },
  { :email => "FACE", :password_digest => "$2a$10$9uapYU3CrXn7knkrsoZTt.jRXiOd7s8RGLUIJFF9shRORKYvuVTZq", :created_at => "2013-07-09 15:42:18", :updated_at => "2013-07-09 15:58:05", :role => "user" },
  { :email => "NEW", :password_digest => "$2a$10$C2J6S2jR1ksBhdRVYQKezu0um9ceeDqKY.atF7tzgnI8MQiFCR6DS", :created_at => "2013-07-09 16:33:29", :updated_at => "2013-07-09 16:33:29", :role => nil },
  { :email => "ilonakennedy@gmail.com", :password_digest => "$2a$10$qu6e1nOlVo/HWfOWjGjZo.HAU/dKwyVu8Xz7wV5FlrvjF3ZiFS0Re", :created_at => "2013-07-09 22:21:26", :updated_at => "2013-07-09 22:21:26", :role => nil },
  { :email => "alexis@gmail.com", :password_digest => "$2a$10$ShNFcdKk9/HjKO2ZZI543u/xGfcEUuGPHgTVFhuIlNp69x2yY9dSO", :created_at => "2013-07-10 08:27:11", :updated_at => "2013-07-10 08:27:11", :role => nil },
  { :email => "michael", :password_digest => "$2a$10$sjojhCcAQljKMd63JjYrjegyiQ90/c1Qi5a4KT1E7ETzUAIOwlPaG", :created_at => "2013-07-10 08:30:13", :updated_at => "2013-07-10 08:30:13", :role => nil }
], :without_protection => true )


